'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Table
    Public Property C_Id As Integer
    Public Property C_Name As String

    Public Overridable Property Table1 As ICollection(Of Table1) = New HashSet(Of Table1)

End Class
